# Generated by Django 3.1.2 on 2021-04-13 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choise',
            old_name='choise_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='choise',
            old_name='choise_votes',
            new_name='votes',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='text',
        ),
    ]
